name: basic-quality-check
on: [push, pull_request]
jobs:

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Execute pytest
        run: |
          poetry run python -m pytest

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: flake8 check
        run: |
          poetry run python -m flake8 .
      - name: isort check
        run: |
          poetry run python -m isort . --check-only
      - name: black check
        run: |
          poetry run python -m black . -l 79 -S --check
